apiVersion: v1
kind: Service
metadata:
  name: nvr-dashboard
  namespace: nvr
  labels:
    app: nvr-dashboard
spec:
  type: ClusterIP
  selector:
    app: nvr-dashboard
  ports:
    - name: http
      port: 8000
      targetPort: 8000
